name: Pull Request Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_pr:
    name: Pull Request Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20, 22, 24 ] # Node versions before 20 are EoL, but the CLI plugin still supports v18
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
